export const environment = {
  production: true,
  apiLocalUrl: 'https://localhost:7094',
  //apiLocalUrl: 'https://sti-backend.upao.edu.pe',
  apiVersion: 'v1',
  customHeaderName: 'X-UPAO1-Header',
  //customHeaderValue: 'Botija',
  customHeaderValue: 'UPAOUPAO123',
  get apiBaseUrl() {
    return `${this.apiLocalUrl}/api/${this.apiVersion}/`;
  },
  get ticketApiUrl() { return `${this.apiBaseUrl}Ticket`; },
  get sequenceApiUrl() { return `${this.apiBaseUrl}Sequence/`; },
  get asignacionApiUrl() { return `${this.apiBaseUrl}Asignacion/`; },
  get usuariosApiUrl() { return `${this.apiBaseUrl}Usuarios/`; },
  get viaRecepcionApiUrl() { return `${this.apiBaseUrl}viaRecepcion/`; },
  get tipologiaApiUrl() { return `${this.apiBaseUrl}Tipologia/`; },
  get prioridadApiUrl() { return `${this.apiBaseUrl}Prioridad/`; },
  get organizacionApiUrl() { return `${this.apiBaseUrl}Organizacion/`; },
  get categoriaApiUrl() { return `${this.apiBaseUrl}Categoria/`; },
  get cargosApiUrl() { return `${this.apiBaseUrl}Cargos/`; },
  get respuestaApiUrl() { return `${this.apiBaseUrl}Respuesta/`; },
  get asignarCategoriaApiUrl() { return `${this.apiBaseUrl}AsignarCategoria/`; },
  get osieApiUrl() { return `${this.apiBaseUrl}Osie/`; },
  get configUsuarioApiUrl() { return `${this.apiBaseUrl}ConfigUsuario/`; },
  get adjuntoApiUrl() { return `${this.apiBaseUrl}Adjunto/`; },
  get authApiUrl() { return `${this.apiBaseUrl}Auth`; },
  get catalogoN1ApiUrl() { return `${this.apiBaseUrl}CatalogoN1/`; },
  get catalogoN2ApiUrl() { return `${this.apiBaseUrl}CatalogoN2/`; },
  get catalogoN3ApiUrl() { return `${this.apiBaseUrl}CatalogoN3/`; },
  get catalogoApiUrl() { return `${this.apiBaseUrl}Catalogo/`; }, 
  get ticketsHubUrl() { return `${this.apiLocalUrl}/TicketsHub`; },
  get dashboardApiUrl() { return `${this.apiBaseUrl}Dashboard/`; },
  get asignarTicketApiUrl() { return `${this.apiBaseUrl}asignarTicket/`; },
  get asignarCatalogoApiUrl() { return `${this.apiBaseUrl}AsignarCatalogo/`; },
  get tareaTicketApiUrl() { return `${this.apiBaseUrl}TareaTicket/`; },
  get asignarCoordinadorApiUrl() { return `${this.apiBaseUrl}AsignarCoordinador/`; },
  get trabajosApiUrl() { return `${this.apiBaseUrl}trabajos/`; },
  get progresoApiUrl() { return `${this.apiBaseUrl}progreso/`; },
  get registrarTareasApiUrl() { return `${this.apiBaseUrl}registrartareas/`; },
  get etiquetaApiUrl() { return `${this.apiBaseUrl}Etiqueta/`; },
  get registroEtiquetasApiUrl() { return `${this.apiBaseUrl}RegistroEtiquetas/`; },
  get subTareasApiUrl() { return `${this.apiBaseUrl}SubTareas/`; },
  get solucionApiUrl() { return `${this.apiBaseUrl}Solucion`; },
  get historialApiUrl() { return `${this.apiBaseUrl}Historial`; },
  get vinculacionApiUrl() { return `${this.apiBaseUrl}Vinculacion`; },
  get unidadApiUrl() { return `${this.apiBaseUrl}Unidad/`; },
  get respuestaUsuarioApiUrl() { return `${this.apiBaseUrl}RespuestaUsuario/`; },
  get ubicacionApiUrl() { return `${this.apiBaseUrl}Ubicacion/`; },

  endPoint: "http://10.1.22.158:5171/",
  // endPoint: "https://localhost:7142/",
  apiTicket: 'https://localhost:7094/',
  urlSSO: 'https://upaosso.upao.edu.pe:410',
  // urlSSO: 'https://localhost:7258',
  //urlAngular:  'http://localhost:4200',
  urlTickets : 'http://localhost:4200',
  //urlAngular: 'http://10.1.22.158:4200',
  urlAngular: 'http://localhost:4200',
  // urlAngular: 'http://localhost:4200',
  // clientId: 'sti_upao_2024',
  cryptoIv:'1234567890123456',
  jwtSSOKey : "Hs8Rvw8S/5vtxMBGpuzOj14hLRNwwUcfejytxNQp6Uk=",
  // jwtSSOKey : "Y2xhdmVzZWNyZXRhcGFyYWVncmVzYWRvc3VwYW8=",
  // clientAdmi : "egresadoAdmin_1510",
  clientAdmi : "sti_upao_2024",
  cryptoKey:'12345678901234561234567890123456',
};
